LiFE data structure should be updated on setup:upgrade
bold-commerce/m1-bold-checkout pull request #40
Opened 2024-04-30 14:57 UTC by pavel-bystritskyi

2024-04-30 16:01 UTC, TimeBones approved these changes

2024-05-01 07:03 UTC, victor-petryk requested changes

2024-05-01 07:03 UTC, victor-petryk commented on Checkout/sql/bold_checkout_setup/mysql4-data-upgrade-2.0.2-2.0.3.php
> +        $result
```suggestion
        $lifeElements
```

2024-05-01 12:20 UTC, victor-petryk approved these changes

2024-05-08 10:56 UTC, merged